name: epi_nlp
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy>=1.24
  - pandas>=2.0
  - gensim>=4.3
  - scikit-learn>=1.3
  - tqdm>=4.66
  - openpyxl>=3.1
  - xlrd>=2.0
  - statsmodels>=0.14
  - python-docx>=1.1
  - pip:
      - tensorflow>=2.16
